yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView, PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_reset/',
         PasswordResetView.as_view(),
         name='password_reset_form'),
    path('password_change/',
         PasswordChangeView.as_view(),
         name='password_change_form'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='group_posts')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True, db_index=True,
                            verbose_name='URL')
    description = models.TextField()

    class Meta:
        verbose_name = 'Группы по интересам'
        verbose_name_plural = 'Группы по интересам'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавить картинку'
    )

    class Meta:
        verbose_name = 'Посты'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:settings.CUT_TEXT]

yatube/users/models.py
# from django.db import models

# Create your models here.

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Текст поста', 'group': 'Название группы'}
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост'
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    """Переопределение страницы с ошибкой 404."""
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=''):
    """Переопределение страницы с ошибкой 403csrf."""
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User
from .page import paginator


def index(request):
    posts = Post.objects.select_related('author', 'group')
    return render(request, 'posts/index.html',
                  {'page_obj': paginator(posts, request)})


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    return render(request, 'posts/group_list.html',
                  {'group': group, 'page_obj': paginator(posts, request)})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_posts = author.posts.select_related('group')
    return render(request, 'posts/profile.html',
                  {'author': author,
                   'page_obj': paginator(author_posts, request)})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})


@login_required()
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form})

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
  {% block title %}Об авторе проекта{% endblock %}
  {% block content %}
  {% load static %}
    <div class="container py-4">
	  <div class="card my-2">
		<h1 class="card-header display-6">Привет, я автор этого проекта</h1>
		<div class="card-body">
		  <div class="row">
		  <aside class="col-md-4">
			<img class="rounded mx-auto d-block img-fluid" img src="{% static 'img/author.jpg' %}"><br>
		  </aside>
		  <article class="col-md-8">
			<p>Здравствуйте! Меня зовут Урал, я из Башкирии.</p>
            <p>Это мой первый опыт в программировании.</p>
            <p>Я долго шел в этом направлении.</p>
            <p>По специальности я геолог, занимался геологическим моделированием.</p>
            <p>Но в нашей работе было очень много рутины, которую можно было облегчить
                путем написания скриптов на Python.</p>
            <p>И вот я в Яндекс практикуме! И это новый мир!</p>
			<p><a class="text-muted" href="https://github.com/Ural207/" target="_blank">
                Моя страница на GitHub</a></p>
		  </article>
		  </div>
		</div>
	  </div>
    </div>
  {% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <h3 class="display-6">Технологии, которые я использовал:</h3>
    <ul>
      <li class="mb-1">
         Backend написан на языке <span style="color:green">Python</span>
         с применением фреймворка <span style="color:green">Django</span>
      </li>
      <li class="mb-1">
        Frontend на языке разметки <span style="color:green">HTML/CSS</span>
        применением фреймворка <span style="color:green">Bootstrap</span>
      </li>
      <li class="mb-1">
        <span style="color:green">Git/GitHub</span>
        для удобной работы с онлайн-репозиториями и контроля версий кода
      </li>
      <li class="mb-1">
        Редактор кода <span style="color:green">IDE Visual Studio Code</span>
      </li>
    </ul>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock %}
    </title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}Здесь контент{% endblock %}
      </div>
    </main>
      {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/errors.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:green">Ya</span>tube</p>
</footer>

yatube/templates/includes/forms.html
{% load user_filters %}
{% for field in form %} 
<div class="form-group row my-3">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  {{ field|addclass:'form-control' }} 
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
    {% endif %}
</div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="35" height="35" class="d-inline-block align-top" alt="">
        <span style="color:green">Ya</span>tube
      <a/>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
          href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-link link-light">Пользователь: {{ user.username }}</li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>
</header>

yatube/templates/includes/pub.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
    <p>
      {{ post.text }}
    </p>
</article>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}Новая запись{% endblock %}
{% block content %}
<div class="container py-4">
   <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">{% if form.instance.pk %}Редактировать запись
            {% else %}Новая запись{% endif %}
          </div>
            <div class="card-body">
              {% include 'includes/errors.html' %}
            </div>
          <form method="post" action="{% if form.instance.pk %}{% url 'posts:post_edit' form.instance.pk %}
            {% else %}{% url 'posts:post_create' %}{% endif %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'includes/forms.html' %}
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-success">
                {% if form.instance.pk %}Сохранить{% else %}Добавить{% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества{% endblock %}
{% block content %}
  <main>
    <div class="mb-4">
      <div class="mb-3" class="display-5">
        <h1>{{ group }}</h1>
        <h3>{{ group.description|linebreaks }}</h3>
      </div>
    </div>
    {% for post in page_obj %}
    {% include 'includes/pub.html' %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </main>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления {% endblock %}
{% block content %}
<div class="container py-3">
    <div class="mb-4"><h1>Последние обновления на сайте</h1></div>
    {% for post in page_obj %}
    {% include 'includes/pub.html' %}
    {% if post.group %}
      <a class="btn btn-outline-secondary" href="{% url 'posts:group_list' post.group.slug %}"
         role="button"> все записи группы {{ post.group }}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock content%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {% endblock %}
{% block content %}
<div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{ post.pub_date |date:"D d M Y" }}
              </li>
              <li class="list-group-item">
                Группа: {{ post.group }}
              </li>
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            <li class="list-group-item">
              <p>{{ post.text }}</p>
            </li>
            <li class="list-group-item">
              <a class="btn btn-outline-secondary" href="{% url 'posts:post_edit' post.id %}"
              class="btn btn-outline-success btn-sm mb-1">редактировать запись</a>
            </li>
          </article>
        </div>
      </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профиль пользователя{% endblock %}
{% block content %}
  <div class="container py-3">
    <h1>Все посты пользователя {{ author }}</h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% for post in page_obj %}
      <article>
        {% include 'includes/pub.html' %}
      </article>
      <a class="btn btn-outline-secondary" href="{% url 'posts:post_detail' post.pk %}">
        подробная информация</a>
{% if post.group %}
  <a class="btn btn-outline-secondary" href="{% url 'posts:group_list' post.group.slug %}">
    все записи группы</a>
{% endif %}
  <hr>{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% include 'includes/footer.html' %}
{% endblock content %}

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %}
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}